apiVersion: apps/v1 
kind: Deployment
metadata:
  name: demo-ui
spec: 
  selector:
    matchLabels:
      app: demo-ui
  replicas: 1 # tells deployment to run 1 pod matching the template
  template:
    metadata:
      labels:
        app: demo-ui
    spec:
      containers:
      - name: demo-ui
        image: gcr.io/dtc-092021-u509/external-image@sha256:be9b7503210958efa9a5196187ccb91182be6ee29c377591aad033b5ff771e0e
        env: 
        - name: SERVER
          value: "http://demo-service:8082"
        ports:
        - containerPort: 8080
            
        