apiVersion: apps/v1 
kind: Deployment
metadata:
  name: demo-ui
spec: 
  selector:
    matchLabels:
      app: demo-ui
  replicas: 1 # tells deployment to run 1 pod matching the template
  template:
    metadata:
      labels:
        app: demo-ui
    spec:
      containers:
      - name: demo-ui
        image: gcr.io/dtc-092021-u509/external-image@sha256:35175b591cf2d3f2095f9178b62ea5eb17276c05d94a3c004721abaa6e809674
        env: 
        - name: SERVER
          value: "http://demo-service:8082"
        ports:
        - containerPort: 8080
            
        